version: '3.9'
services:
  app1:
    build:
      context: ./services/auth-service
      dockerfile: Dockerfile
    container_name: auth-service
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    command: npm start
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

  app2:
    build:
      context: ./services/payment-service
      dockerfile: Dockerfile
    container_name: node_app2
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
    command: npm start
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

  app3:
    build:
      context: ./services/feedback-service
      dockerfile: Dockerfile
    container_name: node_app3
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=production
    command: npm start
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
