version: '3.9'
services:
  auth:
    build:
      context: ./services/auth-service
      dockerfile: Dockerfile
    container_name: ggashwin/auth-service
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    command: npm start

  payment:
    build:
      context: ./services/payment-service
      dockerfile: Dockerfile
    container_name: ggashwin/payment-service
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
    command: npm start

  feedback:
    build:
      context: ./services/feedback-service
      dockerfile: Dockerfile
    container_name: ggashwin/feedback-service
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=production
    command: npm start
