# app3-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: feedback-deployment
  namespace: nodejs-services
spec:
  replicas: 2
  selector:
    matchLabels:
      app: feedback
  template:
    metadata:
      labels:
        app: feedback
    spec:
      containers:
        - name: feedback
          image: ggashwin/feedback-service:latest
          ports:
            - containerPort: 3002
          env:
            - name: NODE_ENV
              value: "production"
---
apiVersion: v1
kind: Service
metadata:
  name: feedback-service
  namespace: nodejs-services
spec:
  selector:
    app: feedback
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3002
      nodePort: 30002
  type: NodePort