# app2-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payments-deployment
  namespace: nodejs-services
spec:
  replicas: 2
  selector:
    matchLabels:
      app: payments
  template:
    metadata:
      labels:
        app: payments
    spec:
      containers:
        - name: payments
          image: ggashwin/payment-service:latest
          ports:
            - containerPort: 3001
          env:
            - name: NODE_ENV
              value: "production"
---
apiVersion: v1
kind: Service
metadata:
  name: payments-service
  namespace: nodejs-services
spec:
  selector:
    app: payments
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3001
      nodePort: 30001
  type: NodePort
